### ISSUE TITLE
Error: You should wrap your parent component with apollo-provider custom element or ApolloProvider functional component

### ISSUE THREAD

**Issue by Pereslugoff** [ardatan/stencil-apollo#104]
I'm providing my apollo-provider as a wrapper to my apollo-query component and am able to successfully query my backend without any errors. However, I still get 
```Error: You should wrap your parent component with apollo-provider custom element or ApolloProvider functional component```

I originally thought this was because I was not wrapping my entire component in an apollo-provider in my index.html. Not only did that strike me as a weird solution, but the examples seem to be set-up the same way my current project is. Like the examples in this repo, my apollo-provider wraps all children returned in the root parent's return method:

```
const fragmentMatcher = new IntrospectionFragmentMatcher({
  introspectionQueryResultData,
});

const client = new ApolloClient({
  cache: new InMemoryCache({ fragmentMatcher }),
  uri: 'http://localhost:4000/',
});

@Component({
  tag: 'my-banner',
  styleUrl: './my-banner.css',
  shadow: true,
})
export class Banner {
 //Props

  @Watch('//prop')
  onAifChange(newType, oldType) {
    if (newType !== oldType) {
      this.determineQueryParams();
    }
  }

  determineQueryParams = () => {
   //
  };
  render() {
    return (
      <apollo-provider client={client}>
        <apollo-query
          query={GET_QUERY}
          variables={this.determineQueryParams()}
          renderer={({ data, loading }) => {
            if (loading) return <p>Loading</p>;
            const offerType = data.getOffer.offerType;
            if (offerType === 'FIRST') {
              return (
                <first-banner
                  //props
                />
              );
            } else if (offerType === 'SECOND') {
              return (
                <second-banner
                //props
                />
              );
            } else {
              return (
                <third-banner
                //props
                />
              );
            }
          }}
        />
      </apollo-provider>
    );
  }
}

```

My index.html is essentially just:
```
<body>
  <my-banner></my-banner>
</body>
```

To reiterate: component works fine with fetching/rendering and there are no errors other than this one.

**Comment by hiebj** [comment]
I can actually comment on this one. I think this happens when `apollo-query` is a direct child of `apollo-provider` with no intervening component.

I think if you do this the message will go away:

```
render() {
  <apollo-provider ...>
     <my-cmp />
  </apollo-provider>
}
```

my-cmp:
```
render() {
  <apollo-query ...>
     ...
  </apollo-query>
}
```

although I admit this doesn't make sense if the examples do the same thing - with `<apollo-query>` being a direct child of `<apollo-provider>` and it doesn't issue the same warning.
