### ISSUE TITLE
[Feature-Request] SSR support

### ISSUE THREAD

**Issue by pixelmord** [ardatan/stencil-apollo#31]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

SSR support would be fantastic!

sth like `react-apollo` does in `getDataFromTree(App)`
https://github.com/apollographql/react-apollo/blob/master/src/getDataFromTree.ts

Keep up the great work!

**Comment by ardatan** [comment]
Thank you @pixelmord !
I will work on it :)

**Comment by ardatan** [comment]
Must be fixed in https://github.com/ardatan/stencil-apollo/commit/46d9144a0db0ba9e1f4804a99db0a819264912f7

**Comment by patrickhaug** [comment]
Can you give an example snippet? where do we put the Query component then?
