### ISSUE TITLE
stencil-one support

### ISSUE THREAD

**Issue by mikaelkaron** [ardatan/stencil-apollo#47]
Awesome work on `stencil-apollo`, really love it. As the stencil team is moving towards releasing `1.0.0` it would be _awesome_ to have `stencil-apollo` also build for this.

At the moment the main problem I've run into is the dep on `@stencil/state-tunnel@^0.0.8` that causes issues as there's a `@stencil/state-tunnel@one` that is compatible with `@stencil/*@one`

**Comment by mikaelkaron** [comment]
If you want to I can start an initial PR for it

**Comment by mikaelkaron** [comment]
Btw. Look like it’s only the `yarn` file that locks that version. However the root problem is to make the code `@one` compatible so I’ll leave this as-is.

**Comment by ardatan** [comment]
@mikaelkaron Thank you! Sure, you can create a PR for it :)

**Comment by mikaelkaron** [comment]
See #49

**Comment by ardatan** [comment]
Available in 0.1.3 :)

**Comment by mikaelkaron** [comment]
I think there's a publishing error of `0.1.4` on NPM, if I build it locally and link it works fine, but using the NPM version throws typescript errors (JSX related).

So I guess "works in source but not in binary, can you half-close?" ;)

**Comment by ardatan** [comment]
I am using `stencil-apollo` in my different projects. I don't have any JSX related TypeScript error.
Can you give more details?

**Comment by mikaelkaron** [comment]
Yeah, actually I can. I think the problem won't be apparent as it's a bit of an edge case, I personally ran into it because I inline `SVG` in my code an simply importing from `stencil-apollo` caused `ts` warnings related to the `inlist` prop.

After digging around a bit I saw that [global `JSX` was removed](https://github.com/ionic-team/stencil/blob/master/BREAKING_CHANGES.md#removed-global-jsx) in `@one` and while fixing that realized that if you kept `node_modules/@stencil/core/dist/declarations/index.d.ts` hanging around in `stencil-apollo` the `ts` warnings disappeared and _that_ gave me the idea that _maybe_ your internal declarations conflicted with how stencil works now, an old artefakt left behind from `0.18.x` times perhaps?

I've sent a PR addressing this and some other `@one` cleanup in #57 and after applying that patch my builds are happy again.

**Comment by arjunyel** [comment]
I can confirm I'm also getting errors with Stencil 1 functional components

`Missing "h" import for JSX types
In order to load accurate JSX types for components, the "h" function must be imported from "@stencil/core" by each component using JSX. For example: import { Component, h } from '@stencil/core';`

**Comment by yeehaa123** [comment]
@mikaelkaron @ardatan any updates on when this PR is going to be accepted? I'm running into the same edge case (with inline SVG) and cannot find a way to work around it.

The error that I get is: Type '{ inlist: any; class: string; viewBox: string; }' is not assignable to type 'SVGAttributes<SVGElement>'.Property 'inlist' does not exist on type 'SVGAttributes<SVGElement>'.

**Comment by DaSchTour** [comment]
Is there any workaround for this issue? This is really driving me crazy, as I really can't get where is property is coming from.
